# Generated by Django 6.0.1 on 2026-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Laki Laki', 'Laki Laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nip',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
