# Generated by Django 6.0.1 on 2026-01-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_birth_info_user_gender_user_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kelas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nisn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
