# Generated by Django 6.0.1 on 2026-01-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_kelas_user_nisn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('GURU', 'Guru'), ('WALI_MURID', 'Wali Murid')], default='WALI_MURID', max_length=20),
        ),
    ]
