# Generated by Django 6.0.1 on 2026-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WAMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerima', models.CharField(max_length=20)),
                ('pesan', models.TextField()),
                ('status', models.CharField(choices=[('terkirim', 'Terkirim'), ('delay', 'Delay'), ('gagal', 'Gagal')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('setor_hafalan', 'Konfirmasi Setor Hafalan'), ('broadcast_umum', 'Broadcast Umum')], max_length=50, unique=True)),
                ('pesan', models.TextField(help_text='Gunakan tag [nama_siswa], [surah], [nilai]')),
            ],
        ),
    ]
