# Generated by Django 6.0.1 on 2026-01-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wamessagelog',
            name='nama_siswa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
