# Generated by Django 6.0.1 on 2026-01-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_gateway', '0002_wamessagelog_nama_siswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watemplate',
            name='pesan',
            field=models.TextField(help_text='Gunakan tag [nama_siswa], [surah], [nilai],[skor_adab], [predikat_adab], [ket_adab]'),
        ),
    ]
