# Generated by Django 6.0.1 on 2026-01-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wa_gateway', '0003_alter_watemplate_pesan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watemplate',
            name='pesan',
            field=models.TextField(help_text='Gunakan tag [nama_siswa], [surah], [nilai],[ket_adab]'),
        ),
    ]
