# Generated by Django 6.0.1 on 2026-01-15 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50, unique=True)),
                ('target_hafalan', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('musyif', models.ForeignKey(blank=True, limit_choices_to={'role': 'MUSYIF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_diampu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
