# Generated by Django 6.0.1 on 2026-01-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorHafalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('juz', models.CharField(max_length=5)),
                ('surah', models.CharField(max_length=100)),
                ('ayat', models.CharField(max_length=50)),
                ('jenis_setoran', models.CharField(choices=[('Ziyadah', 'Ziyadah'), ('Murajaah', 'Murajaah')], max_length=20)),
                ('nilai', models.CharField(choices=[('A', 'A - Sangat Baik'), ('B', 'B - Baik'), ('C', 'C - Cukup'), ('D', 'D - Kurang'), ('E', 'E - Perlu Bimbingan')], max_length=5)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('musyif', models.ForeignKey(limit_choices_to={'role': 'MUSYIF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hafalan_musyif', to=settings.AUTH_USER_MODEL)),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'WALI_MURID'}, on_delete=django.db.models.deletion.CASCADE, related_name='hafalan_siswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
