# Generated by Django 6.0.1 on 2026-01-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_setorhafalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='setorhafalan',
            name='wa_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='setorhafalan',
            name='nilai',
            field=models.CharField(choices=[('A', 'A - Sangat Baik'), ('B', 'B - Baik'), ('C', 'C - Cukup'), ('D', 'D - Kurang')], max_length=5),
        ),
    ]
