# Generated by Django 6.0.1 on 2026-01-19 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_setorhafalan_wa_sent_alter_setorhafalan_nilai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='musyif',
        ),
        migrations.AddField(
            model_name='kelas',
            name='musyif',
            field=models.ManyToManyField(related_name='kelas_diampu', to=settings.AUTH_USER_MODEL),
        ),
    ]
