# Generated by Django 6.0.1 on 2026-01-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_kelas_musyif_kelas_musyif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelas',
            old_name='musyif',
            new_name='guru',
        ),
        migrations.RemoveField(
            model_name='setorhafalan',
            name='musyif',
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='guru',
            field=models.ForeignKey(limit_choices_to={'role': 'GURU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hafalan_guru', to=settings.AUTH_USER_MODEL),
        ),
    ]
