# Generated by Django 6.0.1 on 2026-01-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_rename_musyif_kelas_guru_remove_setorhafalan_musyif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setorhafalan',
            name='adab_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='adab_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='adab_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='adab_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='deskripsi_adab',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='predikat_adab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='skor_adab',
            field=models.IntegerField(default=0),
        ),
    ]
