# Generated by Django 6.0.1 on 2026-01-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_setorhafalan_adab_1_setorhafalan_adab_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setorhafalan',
            name='wa_sent',
        ),
        migrations.AddField(
            model_name='setorhafalan',
            name='wa_status',
            field=models.CharField(choices=[('pending', 'Belum Dikirim'), ('sent', 'Terkirim'), ('failed', 'Gagal')], default='pending', max_length=20),
        ),
    ]
