# Generated by Django 6.0.1 on 2026-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_remove_setorhafalan_wa_sent_setorhafalan_wa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorhafalan',
            name='jenis_setoran',
            field=models.CharField(choices=[('Ziyadah(Hafalan Baru)', 'Ziyadah(Hafalan Baru)'), ('Murajaah(Mengulang)', 'Murajaah(Mengulang)')], max_length=50),
        ),
    ]
