# Generated by Django 6.0.1 on 2026-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_setorhafalan_jenis_setoran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setorhafalan',
            name='deskripsi_adab',
        ),
        migrations.RemoveField(
            model_name='setorhafalan',
            name='predikat_adab',
        ),
        migrations.RemoveField(
            model_name='setorhafalan',
            name='skor_adab',
        ),
        migrations.AlterField(
            model_name='setorhafalan',
            name='adab_1',
            field=models.TextField(default='-', verbose_name='Integritas'),
        ),
        migrations.AlterField(
            model_name='setorhafalan',
            name='adab_2',
            field=models.TextField(default='-', verbose_name='Sopan Santun'),
        ),
        migrations.AlterField(
            model_name='setorhafalan',
            name='adab_3',
            field=models.TextField(default='-', verbose_name='Disiplin'),
        ),
        migrations.AlterField(
            model_name='setorhafalan',
            name='adab_4',
            field=models.TextField(default='-', verbose_name='Empati'),
        ),
    ]
